version: "3.8"

services:
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    mem_limit: 3g
    cpu_count: 2
    environment:
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 6
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: "true"
    volumes:
      - cosmosdb:/tmp/cosmos/appdata
  godev:
    build:
      context: .
      dockerfile: Dockerfile

    network_mode: service:cosmosdb
    command: sleep infinity

    environment:
      COSMOS__ENDPOINT: https://cosmosdb:8081
      COSMOS__KEY: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==

    volumes:
      - ../..:/workspaces:cached

volumes:
  cosmosdb:
